/** Global-track copy for the approved build 22 training additions. */
export const training22 = {
  entry: 'Already trained? Log this session',
  title: (day: string) => `Quick log · ${day}`,
  history: 'Training history',
  back: 'Back',
  date: 'Training date',
  today: 'Today',
  done: 'Done',
  next: 'Next cell →',
  sync: (count: number) => `Apply to all ${count} sets`,
  auto: 'Auto',
  weight: 'Weight',
  reps: 'Reps',
  include: 'Log',
  skipped: 'Not performed',
  restore: 'Restore sets',
  count: (count: number, total: number) => `${count} / ${total} logged`,
  summary: (exercises: number, sets: number) => `Log ${exercises} exercises · ${sets} sets`,
  empty: 'Include at least one exercise',
  hold: 'Hold · Log and complete session',
  saving: 'Saving session…',
  partial: (saved: number, remaining: number) => `${remaining} sets could not be saved. ${saved} saved sets are safe. Please retry.`,
  completionFailed: 'Your sets are saved, but the session could not be completed. Please retry.',
  invalid: 'Check the training date, weights, repetitions and RPE before saving.',
  locked: 'Saved sets are safe. Retry this submission, or go back to edit the session.',
  saved: (day: string) => `${day} logged`,
  previousMonth: 'Previous month',
  nextMonth: 'Next month',
};
